Update create-issues.yml

diff --git a/.github/workflows/create-issues.yml b/.github/workflows/create-issues.yml
--- a/.github/workflows/create-issues.yml
+++ b/.github/workflows/create-issues.yml
@@ -19,25 +19,32 @@ jobs:
           github-token: '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'
           script: |
             try {
-              const repos = [ 'NuGet/NuGetGallery', 'NuGet/NuGet.Jobs','lyndaidaii/NuGetReadMeTemplate', 'lyndaidaii/TestWithSVG']; // List of repositories
-              const title = 'New Issue Title';
-              const body = 'Description of the issue...';
+              //const repos = [ 'NuGet/NuGetGallery', 'NuGet/NuGet.Jobs','lyndaidaii/NuGetReadMeTemplate', 'lyndaidaii/TestWithSVG']; // List of repositories
+              const packages = {
+                'test packages': 'lyndaidaii/TestWithSVG'
+              };
 
-              async function createIssue(repo) {
+              const body = 'As one of the top most installed NuGet packages, your System.Data.SqlClient package is extremely important to the developer ecosystem. The NuGet team has noticed that your package on NuGet.org is missing a README file. Please take a moment to add a README file to your package repository.\n Our customer research indicates that one of the top problems that package consumers face is insufficient package documentation such as README files. Adding a README file to your package will help users quickly understand what the package is and what it does. Since your README will be the first impression for users when they view your package on NuGet.org, it is crucial for authors to write and include high-quality READMEs for their packages.';
+
+              async function createIssue(repo, packageName) {
                 const [owner, repoName] = repo.split('/');
                 const response = await github.rest.issues.create({
                   owner: owner,
                   repo: repoName,
-                  title: title,
+                  title: '${packageName} is missing NuGet package README file',
                   body: body
                 });
                 console.log(`Issue created in ${repo}:`, response.data.html_url);
               }
 
-              for (const repo of repos) {
-                await createIssue(repo);
-              }
-            } catch (error) {
-              console.error('Error:', error.message);
-              core.setFailed(error.message);
-            }
+              for package in "${packages[@]}"; do{
+                try {
+                  packageName="${package%%=*}"
+                  repo="${package#*=}"
+                  echo "Package: $packageName, Project URL: $projectUrl"
+                  await createIssue(repo, packageName)
+                } catch (error) {
+                  echo "Error occurred while processing package $packageName: $error"
+                  exit 1
+                }
+              done
